function [ answer ] = parameterDialog()
prompt = {'Give an equation for s(k): ', ...
    'Give an equation for v(k): ', ...
    'Give an equation for m(k): ', ...
    'Give training rate alpha: ', ...
    'Give acceptable error threshold: ', ...
    'Give max epocs: ', ... 
    'Give number of samples: '};
dlg_title = 'Input';
num_lines = 1;
defaultans = {'-2 + 4*rand()', ...
    '1.2*sin(2*pi*k/3)', ...
    '.12*sin(2*pi*k/3+pi/2)', ...
    '.12', ...
    '10^-3', ...
    '10^3', ...
    '800'};
answer = inputdlg(prompt,dlg_title,num_lines,defaultans);

end

